### ISSUE TITLE
Use annotated tag?

### ISSUE THREAD

**Issue by MoOx** [MoOx/npmpub#11]
Instead of `git tag 1.0.0`, it seems that `git tag -am "1.0.0" 1.0.0` is better https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags/4971817

Also lightweight tags might not be pushed with --follow-tags https://stackoverflow.com/questions/17219102/how-to-make-git-push-include-tags-within-a-branch/17219399#17219399

**Comment by okonet** [comment]
Why not just use `npm version` or `yarn version` that will take care of tags etc?

**Comment by MoOx** [comment]
The thing is npm/yarn version increment the version in the package.json. And when you handle a changelog by hand, you still have to do a manual commit to bump the version in the changelog. And I found it's not really smart to have to do that: one commit by hand and one automated. You kind of have 2 distinct commit to bump the same thing.

Maybe we could handle this via a pre/postversion hook?

**Comment by okonet** [comment]
I personally don't mind doing 2 commits. To me tagging is more important and I always foget doing it manually.

**Comment by MoOx** [comment]
What is the problem with the current solution?

**Comment by okonet** [comment]
No problem at all but I was wondering if this can be simplified. I like the idea of post hook

**Comment by MoOx** [comment]
Closed by https://github.com/MoOx/npmpub/pull/16
