### ISSUE TITLE
GitHub release failed when trying to publish (404 "Not Found")

### ISSUE THREAD

**Issue by gotofritz** [MoOx/npmpub#14]
Hi. On OS X, node v6.9.1, npm 3.10.8

When I try to publish with `npm run release` (where release is simply `npmpub`) it gets to the end and then I get this error

```
📦  Publishing...
+ xxx@0.1.3
Everything up-to-date

xxx/node_modules/github-release-from-changelog/github-release-from-changelog.js:112
    throw err
    ^
Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
📦  GitHub release failed.
```

**Comment by MoOx** [comment]
This can happen if github is "to slow" to detect the tag npmpub just pushed.
Can you try the following command in your terminal ?

```
./node_modules/github-release-from-changelog/github-release-from-changelog.js
```

Should works.

**Comment by gotofritz** [comment]
I get exactly the same error.

**Comment by MoOx** [comment]
Does the tag of your release exists on github?

**Comment by gotofritz** [comment]
No, it doesn't

**Comment by MoOx** [comment]
[it should](https://github.com/MoOx/npmpub/blob/7f33f16f4d608055d6b0aa1a9007a8d66820e0c7/npmpub.js#L180).

Can you try `git push --follow-tags` and see if that's pushing the git tag? You may have a global git config option that interfer somehow... Not sure what is causing this issue.

**Comment by gotofritz** [comment]
There is no error message or log saying that didn't work. The output on the  CLI is

```
📦  Preparing v0.1.4.
📦  Running 'npm install'. This can take a while.
📦  Running tests...
(a bunch of tests)
📦  Publishing...
+ stylelint-config-pv@0.1.5
Everything up-to-date

./node_modules/github-release-from-changelog/github-release-from-changelog.js:112
    throw err
    ^
Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
📦  GitHub release failed.
```

If I then just run the commend you suggested

```
> ./node_modules/github-release-from-changelog/github-release-from-changelog.js

./node_modules/github-release-from-changelog/github-release-from-changelog.js:112
    throw err
    ^
Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

Tag exists locally but not on github

**Comment by gotofritz** [comment]
Ah sorry, just saw your reply. No, tags do not get pushed... strange. I will investigate, thanks.

**Comment by gotofritz** [comment]
`git push --tags` works. `git push --follow-tags` doesn't. I see from the documentation that 

> The new option "--follow-tags" tells "git push" to push annotated tags that are missing from the other side and that can be reached by the history that is otherwise pushed out.

It seems that [the tag created by npmpub is not annotated](https://github.com/MoOx/npmpub/blob/7f33f16f4d608055d6b0aa1a9007a8d66820e0c7/npmpub.js#L173)

**Comment by MoOx** [comment]
Yeah, see https://github.com/MoOx/npmpub/issues/11
Not sure why it's working for so many people for such a long time haha.
What is your version of git?

**Comment by gotofritz** [comment]
2.9, just updated to 2.11

I have tried changing line 173 to `const gitTag = exec("git tag -a " + version + " -m \"Tag " + version + " created with npmpub\"");` - now the tag _does_ get pushed, but I still get the same error....

**Comment by MoOx** [comment]
``github-release-from-changelog`` should just convert a tag to a github release by pushing your CHANGELOG notes. If the tag is visible on github, it should just work.

**Comment by gotofritz** [comment]
Well github is not happy about something. So there are two issues - one is that npmpub doesn't create annotated tag (I am happy to submit a PR to fix that). The other is that in my case github-release-from-changelog doesn't work for me. Do you want me to open an issue there?

**Comment by gotofritz** [comment]
FYI, this is what I get when I set the github API wrapper to debug

```
REQUEST:  { host: 'api.github.com',
  port: 443,
  path: '/repos/pro-vision/style-config-pv/releases?access_token=xxxx',
  method: 'post',
  headers: 
   { host: 'api.github.com',
     'content-length': 76,
     'content-type': 'application/json; charset=utf-8',
     'user-agent': 'NodeJS HTTP Client',
     accept: 'application/vnd.github.v3+json' },
  ca: undefined }
REQUEST BODY: {"tag_name":"0.1.7","name":"0.1.7","body":"\n-   Fixed publishing issues\n"}

STATUS: 404
HEADERS: {"server":"GitHub.com","date":"Fri, 16 Dec 2016 08:52:05 GMT","content-type":"application/json; charset=utf-8","content-length":"77","connection":"close","status":"404 Not Found","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4997","x-ratelimit-reset":"1481881150","x-oauth-scopes":"public_repo","x-accepted-oauth-scopes":"repo","x-github-media-type":"github.v3; format=json","access-control-expose-headers":"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","content-security-policy":"default-src 'none'","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","x-github-request-id":"xxx"}
[error] { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
[error]   message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
[error]   code: 404,
[error]   status: 'Not Found',
[error]   headers: 
[error]    { server: 'GitHub.com',
[error]      date: 'Fri, 16 Dec 2016 08:52:05 GMT',
[error]      'content-type': 'application/json; charset=utf-8',
[error]      'content-length': '77',
[error]      connection: 'close',
[error]      status: '404 Not Found',
[error]      'x-ratelimit-limit': '5000',
[error]      'x-ratelimit-remaining': '4997',
[error]      'x-ratelimit-reset': '1481881150',
[error]      'x-oauth-scopes': 'public_repo',
[error]      'x-accepted-oauth-scopes': 'repo',
[error]      'x-github-media-type': 'github.v3; format=json',
[error]      'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
[error]      'access-control-allow-origin': '*',
[error]      'content-security-policy': 'default-src \'none\'',
[error]      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
[error]      'x-content-type-options': 'nosniff',
[error]      'x-frame-options': 'deny',
[error]      'x-xss-protection': '1; mode=block',
[error]      'x-github-request-id': 'xxx' } } { owner: 'pro-vision',
[error]   repo: 'style-config-pv',
[error]   tag_name: '0.1.7',
[error]   target_commitish: undefined,
[error]   name: '0.1.7',
[error]   body: '\n-   Fixed publishing issues\n',
[error]   prerelease: undefined } null

```

**Comment by MoOx** [comment]
Did you defined the GITHUB_TOKEN as mentionned in the doc?

**Comment by gotofritz** [comment]
Yes, if I do `echo $GITHUB_TOKEN` it's visible

**Comment by gotofritz** [comment]
- I went https://github.com/settings/tokens created clicked on "personal access tokens"
- clicked on Generate new token
- Ticked on ALL permissions
- in my machine, i put it into a ~/.github_token file
- in my .bash_profile I added `export GITHUB_TOKEN=$(cat $HOME/.github_token)`
- reloaded bash with `. ~/.bash_profile`
- run `echo $GITHUB_TOKEN` to test - got a token.

Am I missing something / doing something wrong?

**Comment by MoOx** [comment]
Not sure what wrong here. You are getting a 404 from github like if you have no right or if the resource not exist.

I just used it a few hours ago without any issue.

Can you share:

- your package npm name (from your package.json/name)
- your repo url

**Comment by MoOx** [comment]
If I go here for example https://api.github.com/repos/MoOx/npmpub/releases I have the releases listed.

You are getting a 404 on https://api.github.com/repos/pro-vision/style-config-pv/releases so you need to check this is accessible. After that should work out of the box.

**Comment by gotofritz** [comment]
You are right. I created a another local repo and it worked.
Thanks for your help.
