### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by soosa** [MoOx/npmpub#17]
Hi, 

I read many issues about this but no solution worked for me.

I am on **npm v5.2.0**, **node v7.9.0** , **macOS 10.12.5**

I am logged in as @soosan ($ npm whoami) and when I try to run `$ npm publish` this error comes up:

`
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 missing : @soosan/npm-excercise
npm ERR! 404 
npm ERR! 404  '@soosan/npm-excercise' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
`

I tried:
$ npm config set @types:registry https://registry.npmjs.org/
$ npm cache clean
$ npm rebuild
$ npm login --scope=soosan
$ npm --access-public publish

deleted node-modules then $npm install
I set git repository in node-package

What am I missing?

**Comment by MoOx** [comment]
Are you using "npmpub"?

**Comment by soosa** [comment]
hmm...I created a new project with different name and managed to publish it.
It looks like it did not like the name "npm-excercise" even though there is no package with that name. 

Thank you for your help.

**Comment by MoOx** [comment]
Weird. Please reopen with more details if you have this issue again!
