### ISSUE TITLE
Explain fatal: ambiguous argument '@'{u}'...HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by koppor** [MoOx/npmpub#19]
I am trying the dry run mode to get used to the tool. However, it outputs `'@'{u}` as revision somehow and therefore does not proceed with uploading. Is this a Windows issue?

```
$ npmpub --debug --dry
📦  git status --porcelain
📦  git fetch --quiet
📦  git rev-list --count --left-only @'{u}'...HEAD
fatal: ambiguous argument '@'{u}'...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
📦  Remote history differ. Please pull changes.
```

**Comment by MoOx** [comment]
git should behave the same on windows right?
Did you see the last line and try to pull before?
Is this a fresh new repo without any commit on the remote?

**Comment by koppor** [comment]
Yeah, git should behave the same on windows :)

Yes, I tried to pull before:

![grafik](https://user-images.githubusercontent.com/1366654/33096353-efce1d7e-cf06-11e7-8fab-69816bdf0fa6.png)

No, commits at remote existing:

![grafik](https://user-images.githubusercontent.com/1366654/33096370-fd7c0f44-cf06-11e7-87c9-4af9487b95d9.png)

Repo URL: https://github.com/adr/adr-log

**Comment by koppor** [comment]
node v8.9.1

**Comment by MoOx** [comment]
To be honest I have no idea.

**Comment by BehindTheMath** [comment]
I have the same error. From my debugging, it seems to me that Git in the Windows command prompt doesn't recognize the single quotes in `@'{u}'`. Running the command without the quotes (`git rev-list --count --left-only @{u}...HEAD`) completes correctly.

Although Bash seems to be able to parse it with the quotes, I don't seem them in [Git's docs](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitrevisions.html).
