### ISSUE TITLE
Compare step is throwing errors when it shouldn't

### ISSUE THREAD

**Issue by BehindTheMath** [MoOx/npmpub#22]
When I was trying to push Pjax v0.2.5, npmpub kept throwing an error `Remote history differ. Please pull changes.`, even though the relevant Git command appeared to be returning the correct value of `"0\n"`.

**Comment by MoOx** [comment]
Hum weird. I am not able to reproduce. Any idea?

**Comment by BehindTheMath** [comment]
I think this is a duplicate of #19.
