### ISSUE TITLE
Warn about the need for a GITHUB_TOKEN

### ISSUE THREAD

**Issue by davidtheclark** [MoOx/npmpub#7]
My build got messed up part-way in because I didn't have a GITHUB_TOKEN added to my environment: https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by MoOx** [comment]
Oh yeah. It's written in doc for https://github.com/MoOx/github-release-from-changelog.
I will add it in doc + add a warning then.

**Comment by MoOx** [comment]
@davidtheclark tell me if instructions looks good to you.

**Comment by davidtheclark** [comment]
Looks great. Thanks!
